// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcMVQg0qo3M6t2wCXtmcCWY6bAM0_qgbA',
    appId: '1:1017149555363:web:3746e8f400ce03338f7516',
    messagingSenderId: '1017149555363',
    projectId: 'chat-app-flutter-beginner',
    authDomain: 'chat-app-flutter-beginner.firebaseapp.com',
    storageBucket: 'chat-app-flutter-beginner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtdHeIxnIpz2edldKNoLwN0S4_1hw5lUw',
    appId: '1:1017149555363:android:cf293e82278810708f7516',
    messagingSenderId: '1017149555363',
    projectId: 'chat-app-flutter-beginner',
    storageBucket: 'chat-app-flutter-beginner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz5tQdWRBHuCqqj8BhrmT-UEQFXVpzUSw',
    appId: '1:1017149555363:ios:1107df5817f5d71f8f7516',
    messagingSenderId: '1017149555363',
    projectId: 'chat-app-flutter-beginner',
    storageBucket: 'chat-app-flutter-beginner.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz5tQdWRBHuCqqj8BhrmT-UEQFXVpzUSw',
    appId: '1:1017149555363:ios:1107df5817f5d71f8f7516',
    messagingSenderId: '1017149555363',
    projectId: 'chat-app-flutter-beginner',
    storageBucket: 'chat-app-flutter-beginner.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcMVQg0qo3M6t2wCXtmcCWY6bAM0_qgbA',
    appId: '1:1017149555363:web:f8946dd9c3b299468f7516',
    messagingSenderId: '1017149555363',
    projectId: 'chat-app-flutter-beginner',
    authDomain: 'chat-app-flutter-beginner.firebaseapp.com',
    storageBucket: 'chat-app-flutter-beginner.firebasestorage.app',
  );
}
